# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetails',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='purchasedetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='PurchaseDetails',
        ),
    ]
