# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
