# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_time',
            name='date_difference',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
