# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_ticket_time_date_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_time',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
