# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20180718_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_time',
            name='date_difference',
        ),
    ]
