# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='bug_or_request',
            field=models.CharField(default='bug', max_length=7),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='value',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
