# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20180709_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
