# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ticket_owner_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
