# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_comment_ticket_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comment_num',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ticket',
            name='upvotes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
