# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20180710_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='upvotes',
            field=models.IntegerField(),
        ),
    ]
