# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20180712_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(default=2),
        ),
    ]
