# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20180712_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(choices=[(1, 'Request New Feature'), (2, 'Report Bug')], default=1),
        ),
    ]
