# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20180713_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(choices=[(1, 'Request New Feature - $99.99'), (2, 'Report Bug - Free')]),
        ),
    ]
