# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20180713_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
